Graphs for Dasshboard
msgbyte/tianji pull request #69
Opened 2024-05-21 22:57 UTC by Its4Nik

Added:
- Toggleable Graphs via Mouse-click
- Some Margins to make it fit better

Channged:
- Moved timespan below the Graph

Mainly (thank youuuu) done by: @[Devsider](https://github.com/Devsider), a good friend of mine.

![image](https://github.com/msgbyte/tianji/assets/106100177/2d206fa9-62d6-4ac1-88f0-4d3834cc4851)
Just imagine the timespan dropdown below the chart.

2024-05-22 04:57 UTC, Its4Nik commented
Also implemented the logic that if a Monitor is a Ping Monitor, it doesnt have the graph property

2024-05-22 13:38 UTC, moonrailgun requested changes
Yeah, thanks your change but its break too much things.

and i think click is not a good idea, because not all people wanna show it.

the best way for it is add a page options to switch it, if people want it.(without click, because no one will know it at first).

(here):
![image](https://github.com/msgbyte/tianji/assets/6964737/9941f253-0914-4c90-884d-c2473f0c946c)



the other thing is `trpc.monitor.data` not a public request. because we dont wanna everyone can visit all data, because maybe its a private data. we should have a new route if we wanna show to public and check is this monitor under current page

2024-05-22 13:38 UTC, moonrailgun commented on docker-compose.yml
emmmm why delete docker compose file?

2024-05-22 13:38 UTC, moonrailgun commented on src/server/v8-compile-cache-0/x64/11.3.244.8-node.17/zSusrzSlocalzSlibzSnode_moduleszScorepackzSdistzSpnpm.js.BLOB
what is those 4 file for?

2024-05-22 13:38 UTC, moonrailgun commented on pnpm-lock.yaml
i think you should not submit this file

2024-05-22 13:38 UTC, moonrailgun commented on src/client/components/monitor/MonitorDataChart.tsx
> +          <Area {...config} />
i think you need prettier.

2024-05-22 13:38 UTC, moonrailgun commented on src/client/store/dashboard.ts
> +  return <MonitorDataChart />;
we dont need dashboard anymore

2024-05-22 14:17 UTC, Its4Nik commented on docker-compose.yml
i deleted it locally because i had another one and there were conflicts, my bad

2024-05-22 14:18 UTC, Its4Nik commented on src/server/v8-compile-cache-0/x64/11.3.244.8-node.17/zSusrzSlocalzSlibzSnode_moduleszScorepackzSdistzSpnpm.js.BLOB
idk where they came from, i think when i built the project those just popped up

2024-05-22 14:21 UTC, Its4Nik commented
Okay so except those issues, from the design just taking the already existing chart is fine?

2024-05-24 09:41 UTC, moonrailgun commented
> Okay so except those issues, from the design just taking the already existing chart is fine?

yeah, current chart is enough. did you have other idea?

2024-05-24 12:06 UTC, Its4Nik commented
> > Okay so except those issues, from the design just taking the already existing chart is fine?
> 
> yeah, current chart is enough. did you have other idea?

well my first Intuition was chartjs or sonething else but that would just be annoying to implement imo. If there is already a chart in the same design why not use it

2024-05-25 12:25 UTC, moonrailgun commented
👍 free feel to re request again after you fixed all problem

2024-06-18 08:27 UTC, SalimQS commented
> Okay so except those issues, from the design just taking the already existing chart is fine?

please, can u continue this, i really think this is a good idea

2024-06-18 09:28 UTC, Its4Nik commented
> > Okay so except those issues, from the design just taking the already existing chart is fine?
> 
> please, can u continue this, i really think this is a good idea

I am working on it, but i have internet problems at home so i dont have much time. But I am going to work on it

2024-06-19 02:24 UTC, SalimQS commented
> > > Okay so except those issues, from the design just taking the already existing chart is fine?
> > 
> > 
> > please, can u continue this, i really think this is a good idea
> 
> I am working on it, but i have internet problems at home so i dont have much time. But I am going to work on it

i hope the best for you, good luck :)

2025-02-01 22:59 UTC, wlock6 approved these changes

2025-02-02 08:12 UTC, closed without merging